// noinspection JSUnusedGlobalSymbols
export enum Mods {
	nm = "nm",
	nf = "nf",
	ez = "ez",
	ts = "ts",
	hd = "hd",
	hr = "hr",
	sd = "sd",
	dt = "dt",
	rx = "rx",
	ht = "ht",
	nc = "nc",
	fl = "fl",
	at = "at",
	so = "so",
	ap = "ap",
	pf = "pf",
	k4 = "k4",
	k5 = "k5",
	k6 = "k6",
	k7 = "k7",
	k8 = "k8",
	fi = "fi",
	rd = "rd",
	cm = "cm",
	tr = "tr",
	k9 = "k9",
	kc = "kc",
	k1 = "k1",
	k3 = "k3",
	k2 = "k2",
	v2 = "v2",
	mr = "mr"
}

// noinspection JSUnusedGlobalSymbols
export enum ModFullName {
	nm = "No Mod",
	nf = "No Fail",
	ez = "Eazy",
	ts = "Touch Screen",
	hd = "Hidden",
	hr = "Hard Rock",
	sd = "Sudden Death",
	dt = "Double Time",
	rx = "Relax",
	ht = "Half Time",
	nc = "Nightcore",
	fl = "Flashlight",
	at = "Auto Play",
	so = "Spun Out",
	ap = "Auto Pilot",
	pf = "Perfect",
	k4 = "4 Keys",
	k5 = "5 Keys",
	k6 = "6 Keys",
	k7 = "7 Keys",
	k8 = "8 Keys",
	fi = "Fade In",
	rd = "Random",
	cm = "Cinema",
	tr = "Target",
	k9 = "9 Keys",
	kc = "Key Coop",
	k1 = "1 Key",
	k3 = "3 Keys",
	k2 = "2 Keys",
	v2 = "Score V2",
	mr = "Mirror"
}

// noinspection JSUnusedGlobalSymbols
export enum ModNum {
	nm,
	nf = 1 << 0,
	ez = 1 << 1,
	ts = 1 << 2,
	hd = 1 << 3,
	hr = 1 << 4,
	sd = 1 << 5,
	dt = 1 << 6,
	rx = 1 << 7,
	ht = 1 << 8,
	nc = 1 << 9,
	fl = 1 << 10,
	at = 1 << 11,
	so = 1 << 12,
	ap = 1 << 13,
	pf = 1 << 14,
	k4 = 1 << 15,
	k5 = 1 << 16,
	k6 = 1 << 17,
	k7 = 1 << 18,
	k8 = 1 << 19,
	fi = 1 << 20,
	rd = 1 << 21,
	cm = 1 << 22,
	tr = 1 << 23,
	k9 = 1 << 24,
	kc = 1 << 25,
	k1 = 1 << 26,
	k3 = 1 << 27,
	k2 = 1 << 28,
	v2 = 1 << 29,
	mr = 1 << 30
}
